#version 450

#extension GL_GOOGLE_include_directive : enable

layout(set = 0, binding = 0) uniform sampler2D image_1;
layout(set = 0, binding = 1) uniform sampler2D image_2;

layout(set = 0, binding = 2, std430) buffer CountChangedPxels
{
    uint count_changed_pixels;
};

#include <gpu_cpu_constants.h>
layout (local_size_x = PBRLIB_WORK_GROUP_SIZE, local_size_y = PBRLIB_WORK_GROUP_SIZE) in;

void main()
{
    ivec2 pixel_coord = ivec2(gl_GlobalInvocationID.xy);

    vec4 pixel_1 = texelFetch(image_1, pixel_coord, 0);
    vec4 pixel_2 = texelFetch(image_2, pixel_coord, 0);

    if (all(greaterThan(abs(pixel_1 - pixel_2), vec4(0.01))))
        atomicAdd(count_changed_pixels, 1);
}