#version 450

#extension GL_GOOGLE_include_directive  : enable
#extension GL_EXT_shader_atomic_float   : enable 

layout(set = 0, binding = 0) uniform sampler2D image_1;
layout(set = 0, binding = 1) uniform sampler2D image_2;

layout(set = 0, binding = 2, std430) buffer MSE
{
    float group_float_errors[];
};

#ifdef PBRLIB_GENERATE_DIFF_IMAGE
layout(set = 0, binding = 3) uniform writeonly image2D image_diff;
#endif

#include <gpu_cpu_constants.h>
layout (local_size_x = PBRLIB_WORK_GROUP_SIZE, local_size_y = PBRLIB_WORK_GROUP_SIZE) in;

void main()
{
    ivec2 pixel_coord   = ivec2(gl_GlobalInvocationID.xy);
    ivec2 image_size    = textureSize(image_1, 0); 

    vec4 pixel_1 = texelFetch(image_1, pixel_coord, 0);
    vec4 pixel_2 = texelFetch(image_2, pixel_coord, 0);

    vec4    diff        = pixel_1 - pixel_2;
    float   sq_error    = dot(diff, diff);

    uint num_group_x = (image_size.x + PBRLIB_WORK_GROUP_SIZE - 1) / PBRLIB_WORK_GROUP_SIZE;
    uint group_index = gl_WorkGroupID.y * num_group_x + gl_WorkGroupID.x;

    atomicAdd(group_float_errors[group_index], sq_error);

    // bool is_diff = any(greaterThan(abs(pixel_1 - pixel_2), vec4(0.1)));

    // if (is_diff)
    //     atomicAdd(count_changed_pixels, 1);

#ifdef PBRLIB_GENERATE_DIFF_IMAGE
    // vec4 color = vec4(vec3(0), 1);
    // if (is_diff)
    //     color = abs(pixel_1 - pixel_2);

    // imageStore(image_diff, ivec2(gl_GlobalInvocationID.xy), color);
#endif
}
