namespace pbrlib::backend::utils
{
    const std::unordered_map<SDL_Keycode, Keycode> sdl_to_pbrlib_keycode
    {
        {SDLK_A, Keycode::A},
        {SDLK_B, Keycode::B},
        {SDLK_C, Keycode::C},
        {SDLK_D, Keycode::D},
        {SDLK_E, Keycode::E},
        {SDLK_F, Keycode::F},
        {SDLK_G, Keycode::G},
        {SDLK_H, Keycode::H},
        {SDLK_I, Keycode::I},
        {SDLK_J, Keycode::J},
        {SDLK_K, Keycode::K},
        {SDLK_L, Keycode::L},
        {SDLK_M, Keycode::M},
        {SDLK_N, Keycode::N},
        {SDLK_O, Keycode::O},
        {SDLK_P, Keycode::P},
        {SDLK_Q, Keycode::Q},
        {SDLK_R, Keycode::R},
        {SDLK_S, Keycode::S},
        {SDLK_T, Keycode::T},
        {SDLK_U, Keycode::U},
        {SDLK_V, Keycode::V},
        {SDLK_W, Keycode::W},
        {SDLK_X, Keycode::X},
        {SDLK_Y, Keycode::Y},
        {SDLK_Z, Keycode::Z},

        {SDLK_0, Keycode::N0},
        {SDLK_1, Keycode::N1},
        {SDLK_2, Keycode::N2},
        {SDLK_3, Keycode::N3},
        {SDLK_4, Keycode::N4},
        {SDLK_5, Keycode::N5},
        {SDLK_6, Keycode::N6},
        {SDLK_7, Keycode::N7},
        {SDLK_8, Keycode::N8},
        {SDLK_9, Keycode::N9},

        {SDLK_F1, Keycode::F1},
        {SDLK_F2, Keycode::F2},
        {SDLK_F3, Keycode::F3},
        {SDLK_F4, Keycode::F4},
        {SDLK_F5, Keycode::F5},
        {SDLK_F6, Keycode::F6},
        {SDLK_F7, Keycode::F7},
        {SDLK_F8, Keycode::F8},
        {SDLK_F9, Keycode::F9},
        {SDLK_F10, Keycode::F10},
        {SDLK_F11, Keycode::F11},
        {SDLK_F12, Keycode::F12},

        {SDLK_SPACE, Keycode::Space},
        {SDLK_RETURN, Keycode::Enter},
        {SDLK_LSHIFT, Keycode::ShiftLeft},
        {SDLK_RSHIFT, Keycode::ShiftRight},
        {SDLK_ESCAPE, Keycode::Escape},

        {SDLK_TAB, Keycode::Tab},
        {SDLK_APOSTROPHE, Keycode::Quote},
        {SDLK_SLASH, Keycode::Slash},
        {SDLK_CAPSLOCK, Keycode::Capslock},

        {SDLK_PLUS, Keycode::Plus},
        {SDLK_MINUS, Keycode::Minus},

        {SDLK_LALT, Keycode::AltLeft},
        {SDLK_RALT, Keycode::AltRight},

        {SDLK_LCTRL, Keycode::CtrlLeft},
        {SDLK_RCTRL, Keycode::CtrlRight},

        {SDLK_BACKSPACE, Keycode::Backspace},

        {SDLK_UP, Keycode::Up},
        {SDLK_DOWN, Keycode::Down},
        {SDLK_RIGHT, Keycode::Right},
        {SDLK_LEFT, Keycode::Left},
    };
}