#version 460

#extension GL_GOOGLE_include_directive : enable

layout(set = 0, binding = 0) uniform sampler2D          input_image;
layout(set = 0, binding = 1) uniform writeonly image2D  result;

#include <gpu_cpu_constants.h>
layout (local_size_x = PBRLIB_WORK_GROUP_SIZE, local_size_y = PBRLIB_WORK_GROUP_SIZE) in;

void main()
{
    ivec2   pixel_coord = ivec2(gl_GlobalInvocationID.xy);
    imageStore(result, pixel_coord, vec4(0.5, 0.2, 0.6, 1.0));
}