name: windows-continuous

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: 
      - '**'
jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Remove SDL_build_config.h
        uses: JesseTG/rm@v1.0.3
        with:
          path: third_party\SDL\include\build_config\SDL_build_config.h

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.0.0
        with:
          vulkan_version: 1.4.304.0
          optional_components: com.lunarg.vulkan.vma
          install_runtime: true
          cache: true
          stripdown: true

      - name: Build tests
        run: |
          mkdir build 
          cd build 
          cmake -DCMAKE_BUILD_TYPE=Release -DPBRLIB_ENABLE_TESTS=ON -DPBRLIB_SETUP_CI=OFF ..
          cmake --build . --config Release --target pbrlib-tests

      - name: Setup SwiftShader
        run: |
          mkdir CI
          cd CI
          git clone https://github.com/google/swiftshader.git
          cd swiftshader
          git submodule update --init --recursive
          cd build
          cmake .. -DREACTOR_BACKEND=Subzero -Thost=x64
          cmake --build . --config Release --target vk_swiftshader
          cp "${{github.workspace}}/CI/swiftshader/build/Windows/vk_swiftshader.dll" "${{github.workspace}}/build/bin/Release/vk_swiftshader.dll"
          cp "${{github.workspace}}/CI/swiftshader/build/Windows/vk_swiftshader_icd.json" "${{github.workspace}}/build/bin/Release/vk_swiftshader_icd.json"
          cp "${{github.workspace}}/CI/swiftshader/build/Windows/vulkan-1.dll" "${{github.workspace}}/build/bin/Release/vulkan-1.dll"

      - name: Run tests
        run: |
          cd build/bin/Release
          ./pbrlib-tests.exe
